[package]
name = "igic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pratt = "0.4.0"
pest = "2.7.10"
pest_derive = "2.7.10"
rustyline = "11"
regex = "1.11.1"
colored = "2.0"
