name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-src
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build release binary
        run: |
          cd igic
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare package
        run: |
          mkdir -p pkg/${{ matrix.target }}
          BIN=igic
          [ "${{ matrix.target }}" = "x86_64-pc-windows-gnu" ] && BIN=igic.exe
          cp igic/target/${{ matrix.target }}/release/${BIN} pkg/${{ matrix.target }}/
          mkdir -p pkg/${{ matrix.target }}/libraries
          cp igic/src/libraries/*.gic pkg/${{ matrix.target }}/libraries/

      - name: Zip package
        run: |
          cd pkg/${{ matrix.target }}
          zip -r ../../igic-${{ matrix.target }}.zip .

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            igic-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}