name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build static release binary with musl
        run: |
          cd igic
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Copy binary and .gic files
        run: |
          mkdir -p igic-linux
          cp igic/target/x86_64-unknown-linux-musl/release/igic igic-linux/
          find igic/src/libraries -name '*.gic' -exec cp {} igic-linux/ \;

      - name: Create zip archive
        run: zip -r igic-linux.zip igic-linux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: igic-linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: |
          cd igic
          cargo build --release

      - name: Copy binary and .gic files (Windows)
        shell: pwsh
        run: |
          mkdir igic-win
          Copy-Item igic/target/x86_64-pc-windows-msvc/release/igic.exe igic-win/
          Get-ChildItem -Recurse -Filter *.gic -Path igic/src/libraries | Copy-Item -Destination igic-win/

      - name: Create zip archive
        run: Compress-Archive -Path igic-win -DestinationPath igic-win.zip
        shell: pwsh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: igic-win.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: |
          cd igic
          cargo build --release

      - name: Package
        run: |
          mkdir -p igic-macos/libraries
          cp igic/target/release/igic igic-macos/
          find igic/src/libraries -name '*.gic' -exec cp {} igic-macos/ \;
          zip -r igic-macos.zip igic-macos

      - uses: softprops/action-gh-release@v2
        with:
          files: igic-macos.zip