name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust and musl target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          targets: x86_64-unknown-linux-musl

      - name: Build static release binary with musl
        run: |
          cd igic
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Copy binary and .gic files
        run: |
          mkdir -p igic-linux
          cp igic/target/x86_64-unknown-linux-musl/release/igic igic-linux/
          cp -r igic/src/libraries/*.gic igic-linux/ || true

      - name: Create zip archive
        run: zip -r igic-linux.zip igic-linux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: igic-linux.zip

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: |
          cd igic
          cargo build --release

      - name: Copy binary and .gic files
        run: |
          mkdir -p igic-win
          cp igic/target/release/igic.exe igic-win/
          cp igic/src/libraries/**/*.gic igic-win/ || true

      - name: Create zip archive
        run: zip -r igic-win.zip igic-win

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: igic-linux.zip